# Generated by Django 5.2 on 2025-05-02 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=20)),
                ('experience_years', models.FloatField()),
                ('availability_schedule', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20, unique=True)),
                ('clinic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
            ],
        ),
    ]
