# Generated by Django 5.2 on 2025-06-03 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapist',
            old_name='clinic_id',
            new_name='clinic',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='availability_schedule',
        ),
        migrations.AddField(
            model_name='therapist',
            name='end_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AddField(
            model_name='therapist',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
