# Generated by Django 5.2 on 2025-06-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0002_rename_clinic_id_therapist_clinic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
