# Generated by Django 5.2 on 2025-05-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clinic',
        ),
        migrations.AddField(
            model_name='user',
            name='clinics',
            field=models.ManyToManyField(blank=True, related_name='users', to='clinic.clinic'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='contact_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
