# Generated by Django 5.2 on 2025-06-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_remove_user_clinic_user_clinics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='clinic',
            name='closing_time',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='opening_time',
            field=models.TimeField(blank=True, max_length=20, null=True),
        ),
    ]
