# Generated by Django 5.2 on 2025-06-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_clinic_closing_time_alter_clinic_opening_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='closing_time',
            field=models.TimeField(max_length=20),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='opening_time',
            field=models.TimeField(max_length=20),
        ),
    ]
