# Generated by Django 5.2 on 2025-05-06 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_remove_user_clinic_user_clinics_and_more'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic'),
            preserve_default=False,
        ),
    ]
