# Generated by Django 5.2 on 2025-06-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment_per_therapist_time',
        ),
    ]
