# Generated by Django 5.2 on 2025-05-02 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('patient', '0001_initial'),
        ('therapist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('treatment_notes', models.TextField(max_length=1000)),
                ('next_followup_date', models.DateField(null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapist.therapist')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('patient', 'therapist', 'date'), name='unique_constraint_patient_date_therapist')],
            },
        ),
    ]
